kind: List
apiVersion: v1
metadata:
  name: activemq-artemis-image-streams
  annotations:
    description: ImageStream definitions for ActiveMQ Artemis Broker Container Image
    openshift.io/provider-display-name: ActiveMQ Artemis Cloud
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: activemq-artemis-broker
    annotations:
      openshift.io/display-name: ActiveMQ Artemis Broker
      openshift.io/provider-display-name: ActiveMQ Artemis Cloud
  spec:
    lookupPolicy:
      local: true  
    tags:
    - name: 'LATEST'
      annotations:
        description: ActiveMQ Artemis Broker image.
        iconClass: icon-artemis
        tags: messaging,artemis,xpaas
        supports: amq:1.0,messaging:1.0
        version: 'LATEST'
      from:
        kind: DockerImage
        name: quay.io/arkmq-org/activemq-artemis-broker-kubernetes:0.2.1
